language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
gemfile:
  - gemfiles/Gemfile.actionpack-3.2.x
  - gemfiles/Gemfile.actionpack-4.0.x
  - gemfiles/Gemfile.actionpack-4.1.x
  - gemfiles/Gemfile.actionpack-4.2.x
  - gemfiles/Gemfile.actionpack-5.0.x
  - gemfiles/Gemfile.actionpack-5.1.x
  - Gemfile
